
services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
    environment:
      FLASK_ENV: development
    networks:
      - app-network

  frontend:
    build: ./frontend/ibm_challenge
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/ibm_challenge:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
